trigger:
  none

resources:
  repositories:
  - repository: childrepo
    type: git
    name: TestOrgDec/childrepo
    endpoint: Automatic service connection
    ref: refs/heads/main 
    

#extends:
steps:
  - checkout: childrepo
  - template: templates/hello-beta1.yml@childrepo
