trigger:
  none

resources:
  repositories:
  - repository: childrepo2
    type: git
    name: TestOrgDec/childrepo2
    endpoint: Automatic service connection
    ref: refs/heads/main 
    

#extends:
steps:
  - checkout: childrepo2
  - template: templates/hello-beta1.yml@childrepo2
