trigger: none

pool:
  vmImage: 'windows-latest' # Or specify other Microsoft-hosted agent

steps:
- task: AzureCLI@2
  displayName: Deleting unused ADF resources test scenario
  inputs:
    azureSubscription: 'Manual SC'
    scriptType: "pscore"
    scriptLocation: "inlineScript"
    inlineScript: |
      Install-Module Az.Accounts -Force
  env:
    AZURE_SERVICE_PRINCIPAL: d57f4b3f-6e6a-4a71-a166-7a9d98daa3ca
    AZURE_SERVICE_PRINCIPAL_PASSWORD: 5-i8Q~3cScOhKORuU2R0t_lk36j0w-~JJEgGfcPO
    AZURE_TENANT: dedb034a-eff6-4ec9-a7c7-318ef7f9a2e9