trigger: none
pool:
  vmImage: ubuntu-latest
resources:
  repositories:
  - repository: TestOrgDec
    type: git
    name: TestOrgDec
    ref: refs/heads/master

steps:
- checkout: TestOrgDec
- script: echo "Hello World!"