parameters:
- name: runtimevariable
  displayName: RUN TIME PARAMETER
  values:
  - Dev
  - BBB
  - Staging
 
 
trigger: none
 
steps:
  - checkout: TestOrgDec
  - task: Bash@3
    displayName: 'Test Pipeline for Bash'
    inputs:
      targetType: inline
      script: |
        echo ${{ parameters.runtimevariable }}
        releaseVersion=${{ parameters.runtimevariable }}
        echo $releaseVersion
        echo "##vso[task.setvariable variable=ModelReleaseVersion;]$releaseVersion"
        echo "$(ModelReleaseVersion)"

  - task: Bash@3
    displayName: 'Test Pipeline for Bash'
    inputs:
      targetType: inline
      script: |
        echo "$(ModelReleaseVersion)"