trigger: none

stages:
# -------------------------
# STAGE 1 – BUILD
# -------------------------
- stage: Build
  displayName: "Stage 1 - Build"
  jobs:
  - deployment: BuildDeployment
    displayName: "Build Job"
    environment: Build-Env
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Build stage executed"
            displayName: "Build Step"

# -------------------------
# STAGE 2 – TEST (Approval)
# -------------------------
- stage: Test
  displayName: "Stage 2 - Test"
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: TestDeployment
    displayName: "Test Job"
    environment: Test-Env
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Test stage executed after approval"
            displayName: "Test Step"

# -------------------------
# STAGE 3 – DEPLOY (Approval)
# -------------------------
- stage: Deploy
  displayName: "Stage 3 - Deploy"
  dependsOn: Test
  condition: succeeded()
  jobs:
  - deployment: DeployDeployment
    displayName: "Deploy Job"
    environment: Prod-Env
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Production deployment executed after approval"
            displayName: "Deploy Step"

#Added a line for the test
#Adding Line 2
#Adding Line 3
#Addign Line 4