trigger: none
stages:
# ------------------------
# STAGE 1 – AUTO RUN
# ------------------------
- stage: Build
  displayName: "Stage 1 - Build"
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo "Build completed"
      displayName: "Build Step"

# ------------------------
# STAGE 2 – MANUAL APPROVAL
# ------------------------
- stage: Test
  displayName: "Stage 2 - Test (Manual Approval)"
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: TestDeployment
    displayName: "Test Deployment"
    environment: Test-Env
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Running tests after approval"
            displayName: "Test Step"

# ------------------------
# STAGE 3 – MANUAL APPROVAL
# ------------------------
- stage: Deploy
  displayName: "Stage 3 - Deploy (Manual Approval)"
  dependsOn: Test
  condition: succeeded()
  jobs:
  - deployment: DeployDeployment
    displayName: "Deploy Deployment"
    environment: Prod-Env
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Deploying to production after approval"
            displayName: "Deploy Step"