trigger: none
pool:
   vmImage: ubuntu-latest

variables:
- name: Config.Ref
  value: refs/heads/tagtest
resources:
  repositories:
  - repository: TestOrgDec
    type: git
    name: TestOrgDecrepo
    ref: Config.Ref

steps:
- checkout: TestOrgDec
- script: echo "Hello World!"