trigger: none
pool:
   vmImage: ubuntu-latest

variables:
- name: Config.Ref
  value: refs/heads/tagtest
resources:
  repositories:
  #- repository: TestOrgDec
  - repository: TestOrgDec
    type: git
    name: TestOrgDec
    #name: childrepo
    #ref: Config.Ref
    ref: Config.Ref

  #- repository: TestOrgDec
  - repository: TestOrgDec
    type: git
    #name: TestOrgDec
    name: childrepo
    #ref: Config.Ref
    ref: Config.Ref

steps:
- checkout: TestOrgDec
- checkout: childrepo
- script: echo "Hello World!"