trigger: none
pool:
   vmImage: ubuntu-latest

variables:
- name: C.Ref
  value: refs/heads/BranchTest
resources:
  repositories:
  - repository: TestOrgDec
    type: git
    name: TestOrgDec
    ref: C.Ref

steps:
#- checkout: TestOrgDec
- script: echo "Hello World!"