trigger: none
pool:
   vmImage: ubuntu-latest

#variables:
#- name: Config.Ref
  #value: refs/heads/tagtest

resources:
  repositories:
  - repository: TestOrgDec
    type: git
    name: TestOrgDec
    ref: Config.Ref

  - repository: childrepo
    type: git
    name: childrepo
    ref: Config.Ref

steps:
- checkout: TestOrgDec
- checkout: childrepo
- script: echo "Hello World!"