# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# Added this line
# Added this line 2
# Added this line 3
# Added this line 4
# Added this line after creating the Testbranch
# Added new line to test trigger
# Adding a line
# Lion is always a lion
# Bang Bang

trigger:
- none
pr:
- none

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
